"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "../repository/auth-provider";

export function CustomerSignupForm() { const { signUpCustomer } = useAuth(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [agreed, setAgreed] = useState(false); const [status, setStatus] = useState<{ kind: "success" | "error"; message: string } | null>(null); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirm) return setStatus({ kind: "error", message: "비밀번호 확인이 일치하지 않습니다." }); if (!agreed) return setStatus({ kind: "error", message: "개인정보처리방침에 동의해 주세요." }); const result = await signUpCustomer({ email, password }); setStatus(result.ok ? { kind: "success", message: "회원가입이 완료되었습니다. 고객 계정으로 로그인되었습니다." } : { kind: "error", message: result.message }); }; return <form onSubmit={submit} className="grid gap-5"><Field id="signup-email" label="이메일"><Input id="signup-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></Field><Field id="signup-password" label="비밀번호"><Input id="signup-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /><p className="mt-1 text-xs text-[var(--neutral-500)]">영문과 숫자를 포함해 12자 이상 입력해 주세요.</p></Field><Field id="signup-password-confirm" label="비밀번호 확인"><Input id="signup-password-confirm" type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" /></Field><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} /><span><Link className="underline" href="/privacy">개인정보처리방침</Link>에 동의합니다.</span></label>{status ? <p role={status.kind === "error" ? "alert" : "status"} className={status.kind === "error" ? "text-sm font-semibold text-[var(--danger-600)]" : "rounded-xl bg-green-50 p-3 text-sm font-semibold text-green-800"}>{status.message}</p> : null}<Button type="submit">회원가입</Button><p className="text-center text-sm">이미 계정이 있으신가요? <Link className="font-bold text-[var(--brand-700)]" href="/login">로그인</Link></p></form>; }
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div><Label htmlFor={id}>{label}</Label>{children}</div>; }
